version: '3.8'
services:
  llama_cpp:
    image: bartowski/mergekit:latest
    volumes:
      - '${MODEL_DIR}:/models'
    environment:
      - PUID=1000
      - PGID=1000
    ulimits:
      memlock: -1
    mem_limit: 50gb
    shm_size: '4gb'
    stdin_open: true
    tty: true
    command: [ "mergekit-moe", "--trust-remote-code", "--random-seed", "0", "/mergekit/mergekit_moe_config.yml", "/models" ]
